# Example docker-compose file, adapt for your setup
services:

  mapserver:

    image: justb4/mapserver:8.2.2-1
    build: .

    container_name: mapserver

    environment:
      - MAPSERVER_CONFIG_FILE=/opt/mapserver/mapserver.conf
      - MIN_PROCS=1
      - MAX_PROCS=3
      - MAX_LOAD_PER_PROC=4
      - IDLE_TIMEOUT=20
      - DEBUG=0
      - MAPSERVER_CATCH_SEGV=1

    ports:
      - "8081:80"

    volumes:
      - ./example:/opt/mapserver:rw
